### ISSUE TITLE
Do not fail on missing sources jar if there is no src directory for the jar

### ISSUE THREAD

**Issue by ge0ffrey** [kordamp/pomchecker#10]
I am trying to release with JReleaser to Maven Central and getting these kinds of errors from pomchecker:

`[ERROR]    [nexus2] optaplanner-spring-boot-starter-8.36.0.Alpha1-sources.jar is missing`

The sources plugin is active and Maven Central has accepted this artifact for years.

However this module is special:

- optaplanner-spring-boot-starter has no src directory. It just depends on optaplanner-spring-boot-autoconfigure, optaplanner-core and optaplanner-persistence-jackson. So the maven sources plugin doesn't create a sources jar.

See also https://github.com/jreleaser/jreleaser/discussions/1287

**Comment by aalmiray** [comment]
How are you able to publish without Maven Central failing on `-sources.jar` and `-javadoc.jar`? I thought those were hard requirements for a pom whose packaging is set to `jar` or if it uses the default packaging (which is `jar`).

**Comment by aalmiray** [comment]
PomChecker does not validate if `-sources.jar` is missing. It only checks pom files.

**Comment by aalmiray** [comment]
Correct. This is not pomchecker's responsibility (verify with associated JAR files exist) but rather it's JReleaser's responsibility. There may be POM files for which matching sources and/or javadoc JARs are not provided and Maven Central will accept them. To let JReleaser accept those POM files you must define `artifactOverrides` as described in the guide https://jreleaser.org/guide/latest/reference/deploy/maven/nexus2.html

**Comment by ppalaga** [comment]
Thanks @aalmiray, I have filed https://github.com/jreleaser/jreleaser/issues/1751
