### ISSUE TITLE
Do not fail on missing javadocs jar if there is no src/main/java directory (= no *.class files in jar)

### ISSUE THREAD

**Issue by ge0ffrey** [kordamp/pomchecker#11]
I am trying to release with JReleaser to Maven Central and getting these kinds of errors from pomchecker:

```
[ERROR]    [nexus2] optaplanner-spring-boot-starter-8.36.0.Alpha1-javadoc.jar is missing
[ERROR]    [nexus2] optaplanner-ide-config-8.36.0.Alpha1-javadoc.jar is missing
```

The javadoc plugins are active and Maven Central has accepted these artifacts for years.

However these modules are special:

- optaplanner-spring-boot-starter has no src directory. It just depends on optaplanner-spring-boot-autoconfigure, optaplanner-core and optaplanner-persistence-jackson. So the maven javadoc plugin don't create a javadocs jar.
- optaplanner-ide-config has no java files. So the maven javadoc plugin don't create a javadocs jar.

See also https://github.com/jreleaser/jreleaser/discussions/1287

**Comment by aalmiray** [comment]
PomChecker does not validate if `-javadoc.jar` is missing. It only checks pom files.
