### ISSUE TITLE
Lookup pom.xml in current directory by default

### ISSUE THREAD

**Issue by helpermethod** [kordamp/pomchecker#12]
First of all, great project!

Exactly the help I need to put my library to Maven Central ❤️ !

Now, when I was executing

    pomchecker 

in the root directory of my project, I'd expect `pomchecker` to search for the `pom.xml` in the current directory by default. Wdyt?

Wouldn't mind making the change myself btw.

**Comment by aalmiray** [comment]
That would make the `--file` parameter be optional and look for a `pom.xml` in the current directory, right?

**Comment by helpermethod** [comment]
> That would make the `--file` parameter be optional and look for a `pom.xml` in the current directory, right?

Exactly!

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.10.0` ([Release Notes](https://github.com/kordamp/pomchecker/releases/tag/v1.10.0))
