### ISSUE TITLE
Add subcommand/flag to fix violations?

### ISSUE THREAD

**Issue by helpermethod** [kordamp/pomchecker#13]
A lot of linting tools also provide a means to autofix violations. In the same vein, `pomchecker` could deduce a lot of defaults from git (remote URL, username, developer) or GitHub (description).

Wdyt?

**Comment by aalmiray** [comment]
That would require editing the pom file which only makes sense when it's a `pom.xml` and not a `<artifactId>-<version>.pom` file.

Besides, I don't know how much pomchecker could do. If it tells you that `<license>` is missing, what values should it pick? What if it's `<developers>`? Context is king.

**Comment by helpermethod** [comment]
`<license>` or `<developers>` could e.g. be picked from GitHub / GitLab. But thinking of it, such a functionality may be out of scope for `pomchecker`, and it probably wouldn't help much in most cases.
