### ISSUE TITLE
Guide only shows empty page

### ISSUE THREAD

**Issue by Bukama** [kordamp/pomchecker#19]
I wanted to know what pomchecker is about and so I headed to the linked "guide". But this is only an empty page:

![image](https://github.com/kordamp/pomchecker/assets/4354359/4192172b-051b-4b82-a83f-827017264787)

**Comment by aalmiray** [comment]
Fixed with https://github.com/kordamp/pomchecker/commit/6482f9cc91b9e7ba03c46523374e35cc102f7472
