### ISSUE TITLE
The example on how to execute pomchecker in the blog post is not working

### ISSUE THREAD

**Issue by iemejia** [kordamp/pomchecker#2]
Hello, thanks for creating this tool. I was trying to execute it following the [info in the website](https://andresalmiray.com/announcing-the-pomchecker-project/) doing
```mvn org.kordamp.maven:enforcer-maven-plugin:1.0.0:check-maven-central```
and it did not work, however
```mvn org.kordamp.maven:pomchecker-maven-plugin:1.1.0:check-maven-central```
does, maybe worth to fix it.

**Comment by aalmiray** [comment]
Ah yes, I can see I made a mistake in the blog post, well spotted! It's fixed now. Thanks!

**Comment by iemejia** [comment]
Thanks for fixing it in the website :+1:
